import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/layout/navbar";
import Footer from "./components/layout/footer";

const pingAr = localFont({
  src: [
    {
      path: "../../public/fonts/pingAr/PingAR+LT-Regular.otf",
      weight: "400",
      style: "normal"
    },
    {
      path: "../../public/fonts/pingAr/PingAR+LT-Bold.otf",
      weight: "700",
      style: "normal"
    }
  ]
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${pingAr.className} antialiased w-full min-h-screen bg-gray-50 flex flex-col items-start justify-start text-md text-right`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
