import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/layout/navbar";
import Footer from "./components/layout/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${inter.className} antialiased w-full min-h-screen bg-gray-50 flex flex-col items-start justify-start font-regular text-md text-right`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
